sudo: required
services: 
  - docker
before_install:
  - docker build -t romano71/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run romano71/react-test npm test -- --coverage
after_success:
  - docker build -t romano71/multi-client ./client
  - docker build -t romano71/multi-nginx ./nginx
  - docker build -t romano71/multi-server ./server
  - docker build -t romano71/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push romano71/multi-client
  - docker push romano71/multi-nginx
  - docker push romano71/multi-server
  - docker push romano71/multi-worker
  